### PR TITLE
BigNum.isBigNum via feature detection

### LINKED ISSUE #41: instanceof operator considered harmful
If my deps use two slightly different versions of bignum, we end up with two different instances of the BigNum class and they are not compatible b/c the `instanceof` checking fails [here](https://github.com/justmoon/node-bignum/blob/0021dd78560ddfb7f83b0ff1da2ae4dfaa4d6a96/index.js#L73).

Another approach is to analyze an instance via a type checking method `BigNum.isBigNum(num)`

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #41
> If my deps use two slightly different versions of bignum, we end up with two different instances of the BigNum class and they are not compatible b/c the instanceof checking fails here.
Another approach is to analyze an instance via a type checking method BigNum.isBigNum(num)

use of instanceof [here](https://github.com/justmoon/node-bignum/blob/0021dd78560ddfb7f83b0ff1da2ae4dfaa4d6a96/index.js#L73)

### CODE REVIEW

**Comment by rvagg** [comment]
I _think_ I can get with this, probably not a terrible idea but I have sneaking suspicion I'm overlooking something important!

**Comment by kumavis** [comment]
so here are the generic failure cases:

#### false negative:
> "it really was a BigNum but it returned false"

this could happen if we some ops get/got renamed.
not compatible now, not compatible after feature detection.
**no change.**

#### false positive
> "it really was NOT a BigNum but it returned true"

this could happen if there was some other number object with those same methods AND the user was trying to pass it in.
This wouldn't have worked before and it would probably break now.
**small change in the way it would break**

**Comment by kumavis** [comment]
As for adding all operations calling `isBigNum(num)` I generally agree, but worth nothing they aren't being used on `num`. The actual ops are being called on `this` with `num` as an argument. So really the necessary sauce is in the cpp instead of OpenSSL and I didn't dig that far.

**Comment by kumavis** [comment]
This is a technique @substack introduced to me, maybe he can speak to best practices here, especially  as I see he has the most commits in this repo

**Comment by kumavis** [comment]
Regarding the false positive change in behaviour, it causes an abort instead of an Error:
```js
var assert = require('assert');
var bignum = require('./');

var valid = bignum('42');
var invalid = {};
var falsePositive = {
    badd: true,
    bsub: true,
    bmul: true,
    bdiv: true,
    bmod: true,
};

attempt(function(){
    valid.add(invalid);
});

attempt(function(){
    valid.add(falsePositive);
});

console.log('End of attempts.')

function attempt(fn){
    try {
        fn()
        console.log('completed succesfully.')
    } catch (err) {
        console.log('errored:')
        console.log(err)
    }
}
```
Result:
```
╭─{🌊 } kumavis in ~/Development/Node/node-bignum on (master✱) 
╰─± node x.js
errored:
[TypeError: Unspecified operation for type object for add]
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file /Users/kumavis/.node-gyp/0.10.35/src/node_object_wrap.h, line 61.
[1]    86545 abort      node x.js
```
Notice it never reached `console.log('End of attempts.')`.

I think it would be hard to get here, but it would be nice if it errored instead of hard crashing. I don't know how to change that behaviour.

**Comment by kumavis** [comment]
@justmoon @rvagg I think this is worth merging.
* It shouldn't make anything that currently works stop working.
* Some things that didn't work now do.
* And some things that didn't work still don't.

**Comment by kumavis** [comment]
If you think stricter type checking is necessary I understand.
Since [all the methods are defined on the Class as well](https://github.com/kumavis/node-bignum/blob/783205424762adccc121dd0d1d4f12128bf13690/index.js#L427-L441) we may need to expect those to be present on the object in order for it to be a BigNum.

There's also something weird going on here.
https://github.com/kumavis/node-bignum/blob/783205424762adccc121dd0d1d4f12128bf13690/index.js#L282-L285

**Comment by kumavis** [comment]
A more conservative and programmatic check would be
```js
BigNum.isBigNum = function(num) {
    var compatible = true;
    for(var key in BigNum.prototype) {
        if (!BigNum.prototype[key]) {
            compatible = false;
        }
    }
    return compatible;
};
```

**Comment by Meekohi** [comment]
Might as well early abort:
```javascript
BigNum.isBigNum = function(num) {
    for(var key in BigNum.prototype) {
        if (!BigNum.prototype[key]) {
            return false;
        }
    }
    return true;
};
```

**Comment by kumavis** [comment]
@Meekohi thanks. Updated version:
```js
BigNum.isBigNum = function(num) {
    if (!num) {
        return false;
    }
    for(var key in BigNum.prototype) {
        if (!num[key]) {
            return false;
        }
    }
    return true;
};
```

**Comment by kumavis** [comment]
Do people prefer this stricter checking? It means things will stop working if we add a method. Which could be a good thing as it would prevent the following undefined behaviour.
```js
bn = BigNumFromSomeDepWithoutNewOp()
BigNum.newOp(bn)
```

**Comment by kumavis** [comment]
I'm content with the conservative type checking. It meets the following criteria:
* Things that currently work still work.
* Some things that didn't work now do.
* Some things that didn't work still don't.

If issues arise in the future regarding interop we can address them, but there is **no interop** right now, so this is an improvement.

**Comment by kumavis** [comment]
If folks agree I'll update the PR and we can merge this.

**Comment by Meekohi** [comment]
I like it. As @kumavis points out people should think of `isBigNum` as `isBugNumWithSameVersionAsMe` anyway.

**Comment by wanderer** [comment]
:+1:

**Comment by tracker1** [comment]
Just a minor suggestion... matching on typeof, not just the existance of properties...

```
BigNum.isBigNum = function(num) {
  for (var key in BigNum.prototype) {
    if (typeof BigNum.prototype[key] !== typeof num[key]) {
      return false;
    }
  }
  return true;
}
```

**Comment by kumavis** [comment]
fine by me, @justmoon any thoughts?

**Comment by kumavis** [comment]
I think false positives are going to be a minority

**Comment by rvagg** [comment]
published as v0.10.0, thanks for the work here

**Comment by kumavis** [comment]
:joy_cat:

**Pull request merged**
