### PR TITLE
Upgrade to NAN v2

### PR DESCRIPTION
**Pull request by rvagg**
WIP, NAN v2 not yet released but this gives us io.js v3 and Node.js v4 (or maybe v5) support.

### CODE REVIEW

**Comment by rvagg** [comment]
fixed up some bugs, this is all good to go now as soon as nan@2 is released

```
$ dnt
node@v0.12.7 : PASS wrote output to /tmp/bignum-dnt-v0.12.7.out
node@v0.10.40: PASS wrote output to /tmp/bignum-dnt-v0.10.40.out
iojs@v1.8.4  : PASS wrote output to /tmp/bignum-dnt-v1.8.4.out
iojs@v2.3.4  : PASS wrote output to /tmp/bignum-dnt-v2.3.4.out
iojs@v3.0.0-rc.3: PASS wrote output to /tmp/bignum-dnt-v3.0.0-rc.3.out
iojs@v2.0.1  : PASS wrote output to /tmp/bignum-dnt-v2.0.1.out
Took 93s to run 6 versions of Node
```

**Comment by iamstarkov** [comment]
@rvagg  @justmoon can it be merged? my packages based on bignum failed to work on iojs@3.0 =(

**Comment by rvagg** [comment]
done, v0.11.0

**Comment by iamstarkov** [comment]
thank you

**Pull request closed without merging**
